name: conda2
on:
  workflow_dispatch:
jobs:
  example-2-linux:
    name: Ex2 Linux
    runs-on: "ubuntu-latest"
    steps:
      - uses: conda-incubator/setup-miniconda@v1
        with:
          miniconda-version: "latest"
          activate-environment: cellpy
      - name: Bash
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda env install --file environment.yml
      - name: PowerShell Core
        shell: pwsh
        run: |
          conda info
          conda list
