name: conda
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: [3.7, 3.8]
    name: Python ${{ matrix.python-version }} example on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
      - run: conda --version
      - run: which python
      - name: Install dependencies
        run: |
          conda env update --file environment.yml --name base
      - name: Test with pytest
        run: |
          conda install pytest
          pytest
      - name: Test cellpy
        run: |
          cellpy info -v
          cellpy info -l
          cellpy info -p
          cellpy info -c
