name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [windows-latest]
    steps:
    - run: echo $CONDA
    - run: dir

      
