name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [windows-latest]
    steps:
    - run: |
        echo %CONDA%
        dir
        set
      shell: cmd
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        %CONDA% env update --file environment.yml --name base

      
